vich_uploader:
    db_driver: orm

    mappings:
        work_images:
            uri_prefix: /assets/images/uploads/works
            upload_destination: '%kernel.project_dir%/public/assets/images/uploads/works'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
